/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9TlqT0rNOcL
 */

import { GuestbookType } from '@/types/guestbook'
import { GUESTBOOK_DUMMY_DATA } from '@/utils/dummy'
import Image from 'next/image'

export function GuestbookDetailModal({
  guestbook_id,
  isOpen,
  closeModal,
}: {
  guestbook_id: string
  isOpen: boolean
  closeModal: () => void
}) {
  const data = GUESTBOOK_DUMMY_DATA.find(
    (data) => data.guestbook_id === guestbook_id,
  ) as GuestbookType

  return (
    isOpen && (
      <div
        className="w-screen h-screen fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-5"
        onClick={closeModal}
      >
        <div className="mx-auto rounded-lg pb-8 p-10 pb-11 bg-white w-fit shadow">
          <div className="space-y-4">
            <div className="space-y-2">
              <h1 className="text-2xl font-bold">
                {data.guestbook_author_nickname}
              </h1>
              <p className="text-sm leading-none text-gray-500 dark:text-gray-400">
                방명록 ID: {data.guestbook_id}
              </p>
              <p className="text-sm leading-none text-gray-500 dark:text-gray-400">
                작성일: {data.guestbook_created_at}
              </p>
            </div>
            <div className="space-y-2">
              <h2 className="text-xl font-semibold">내용</h2>
              <p className="text-base leading-snug text-gray-500 dark:text-gray-400">
                {data.guestbook_content}
              </p>
            </div>
            <div className="grid grid-cols-2 gap-4 space-y-2">
              <div className="space-y-2">
                <h2 className="text-xl font-semibold">작성자</h2>
                <div className="flex items-center space-x-2">
                  <Image
                    alt="Avatar"
                    className="rounded-full"
                    height={32}
                    src={data.guestbook_author_profile_img}
                    style={{
                      aspectRatio: '32/32',
                      objectFit: 'cover',
                    }}
                    width={32}
                  />
                  <div className="space-y-0.5">
                    <p className="text-sm font-medium leading-none dark:text-gray-100">
                      @{data.guestbook_author_nickname}
                    </p>
                    <p className="text-xs leading-none text-gray-500 dark:text-gray-400">
                      작성자 ID: {data.guestbook_author_id}
                    </p>
                  </div>
                </div>
              </div>
              <div className="space-y-2">
                <h2 className="text-xl font-semibold">작가</h2>
                <div className="flex items-center space-x-2">
                  <Image
                    alt="Avatar"
                    className="rounded-full"
                    height={32}
                    src={data.photographer_profile_img}
                    style={{
                      aspectRatio: '32/32',
                      objectFit: 'cover',
                    }}
                    width={32}
                  />
                  <div className="space-y-0.5">
                    <p className="text-sm font-medium leading-none dark:text-gray-100">
                      @{data.photographer_nickname}
                    </p>
                    <p className="text-xs leading-none text-gray-500 dark:text-gray-400">
                      Photographer ID: {data.photographer_id}
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className="space-y-2">
              <h2 className="text-xl font-semibold">신고건수</h2>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <h3 className="text-lg font-semibold">사진</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    {data.guestbook_abusing_report_count}건
                  </p>
                </div>
                <div>
                  <h3 className="text-lg font-semibold">방명록</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    5건
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  )
}
