/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9TlqT0rNOcL
 */

import { getPhoto } from '@/api/photo'
import { IPost, IPostDetail } from '@/types/post'
import { UseQueryResult, useQuery } from '@tanstack/react-query'
import Error from 'next/error'
import Image from 'next/image'

const dummyThumbnail = 'https://picsum.photos/400/225'
const dummyProfile = 'https://picsum.photos/32'

export function PostDetailModal({
  photo_id,
  isOpen,
  closeModal,
}: {
  photo_id: string
  isOpen: boolean
  closeModal: () => void
}) {
  const { data }: UseQueryResult<IPostDetail> = useQuery({
    queryKey: ['photo', photo_id],
    queryFn: () => getPhoto(photo_id),
    enabled: isOpen,
  })

  return (
    isOpen && (
      <div
        className="w-screen h-screen fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-5"
        onClick={closeModal}
      >
        <div className="grid md:grid-cols-2 gap-6 mx-auto rounded-2xl py-9 pr-9 pl-10 bg-white w-[900px] shadow">
          <div className="space-y-4">
            <div className="space-y-2">
              <h1 className="text-2xl font-bold">{data?.exhibition_title}</h1>
              <p className="text-sm leading-none text-gray-500">사진 ID: {data?.photo_id}</p>
              <p className="text-sm leading-none text-gray-500">작성일: {data?.created_at}</p>
            </div>
            <div className="space-y-2">
              <h2 className="text-lg font-semibold">내용</h2>
              <p className="text-base leading-snug text-gray-500">{data?.description}</p>
            </div>
            <div className="space-y-2">
              <h2 className="text-lg font-semibold">작가</h2>
              <div className="flex items-center space-x-2">
                <Image
                  alt="Avatar"
                  className="rounded-full"
                  height={32}
                  // src={data!.profile_img_url}
                  src={dummyProfile}
                  style={{
                    aspectRatio: '32/32',
                    objectFit: 'cover',
                  }}
                  width={32}
                />
                <div className="space-y-0.5">
                  <p className="text-sm font-medium leading-none">@{data?.nickname}</p>
                  <p className="text-xs leading-none text-gray-500">ID: {data?.writer_id}</p>
                </div>
              </div>
            </div>
            <div className="space-y-2">
              <h2 className="text-lg font-semibold">신고건수</h2>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <h3 className="font-semibold">사진</h3>
                  <p className="text-sm text-gray-500">{data?.photo_report_received_count}건</p>
                </div>
                <div>
                  <h3 className="font-semibold">작가</h3>
                  <p className="text-sm text-gray-500">{data?.user_report_received_count}건</p>
                </div>
              </div>
            </div>
          </div>
          <div className="space-y-4 flex items-center">
            <Image
              alt="Photo"
              className="aspect-3/2 object-cover rounded-lg overflow-hidden border border-gray-200"
              height={533}
              // src={data!.photo_img_url}
              src={dummyThumbnail}
              width={800}
            />
          </div>
        </div>
      </div>
    )
  )
}
