import type { Metadata } from 'next'
import './globals.css'
import { QueryClientProvider } from '@/providers/QueryClientProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body id="root">
        <QueryClientProvider>{children}</QueryClientProvider>
      </body>
    </html>
  )
}
