export const POST_DUMMY_DATA = [
  {
    photo_id: '1',
    photo_title: 'Exhibition1',
    photo_description: 'Description1',
    photo_url: '/images/testImage (1).png',
    photo_created_at: '2023-01-01',
    photographer_id: '2023010101',
    photographer_nickname: 'Asher',
    photographer_profile_img: '/images/profile1.png',
    photo_abusing_report_count: 5,
    photographer_photo_abusing_report_count: 6,
  },
  {
    photo_id: '2',
    photo_title: 'Exhibition2',
    photo_description: 'Description2',
    photo_url: '/images/testImage (2).png',
    photo_created_at: '2023-01-02',
    photographer_id: '2023010102',
    photographer_nickname: 'Su bin',
    photographer_profile_img: '/images/profile2.png',
    photo_abusing_report_count: 2,
    photographer_photo_abusing_report_count: 2,
  },
  {
    photo_id: '3',
    photo_title: 'Exhibition3',
    photo_description: 'Description3',
    photo_url: '/images/testImage (3).png',
    photo_created_at: '2023-01-03',
    photographer_id: '2023010103',
    photographer_nickname: 'Je Koo',
    photographer_profile_img: '/images/profile3.png',
    photo_abusing_report_count: 3,
    photographer_photo_abusing_report_count: 3,
  },
  {
    photo_id: '4',
    photo_title: 'Exhibition4',
    photo_description: 'Description4',
    photo_url: '/images/testImage (4).png',
    photo_created_at: '2023-01-04',
    photographer_id: '2023010104',
    photographer_nickname: 'Han Kyeol',
    photographer_profile_img: '/images/profile4.png',
    photo_abusing_report_count: 4,
    photographer_photo_abusing_report_count: 4,
  },
  {
    photo_id: '5',
    photo_title: 'Exhibition5',
    photo_description: 'Description5',
    photo_url: '/images/testImage (5).png',
    photo_created_at: '2023-01-05',
    photographer_id: '2023010105',
    photographer_nickname: 'JUN SEO',
    photographer_profile_img: '/images/profile1.png',
    photo_abusing_report_count: 5,
    photographer_photo_abusing_report_count: 5,
  },
  {
    photo_id: '6',
    photo_title: 'Exhibition6',
    photo_description: 'Description6',
    photo_url: '/images/testImage (6).png',
    photo_created_at: '2023-01-06',
    photographer_id: '2023010106',
    photographer_nickname: 'Asher',
    photographer_profile_img: '/images/profile2.png',
    photo_abusing_report_count: 6,
    photographer_photo_abusing_report_count: 6,
  },
  {
    photo_id: '7',
    photo_title: 'Exhibition7',
    photo_description: 'Description7',
    photo_url: '/images/testImage (7).png',
    photo_created_at: '2023-01-07',
    photographer_id: '2023010107',
    photographer_nickname: 'Su bin',
    photographer_profile_img: '/images/profile3.png',
    photo_abusing_report_count: 7,
    photographer_photo_abusing_report_count: 7,
  },
  {
    photo_id: '8',
    photo_title: 'Exhibition8',
    photo_description: 'Description8',
    photo_url: '/images/testImage (8).png',
    photo_created_at: '2023-01-08',
    photographer_id: '2023010108',
    photographer_nickname: 'Je Koo',
    photographer_profile_img: '/images/profile4.png',
    photo_abusing_report_count: 8,
    photographer_photo_abusing_report_count: 8,
  },
  {
    photo_id: '9',
    photo_title: 'Exhibition9',
    photo_description: 'Description9',
    photo_url: '/images/testImage (1).png',
    photo_created_at: '2023-01-09',
    photographer_id: '2023010109',
    photographer_nickname: 'Han Kyeol',
    photographer_profile_img: '/images/profile1.png',
    photo_abusing_report_count: 9,
    photographer_photo_abusing_report_count: 9,
  },
  {
    photo_id: '10',
    photo_title: 'Exhibition10',
    photo_description: 'Description10',
    photo_url: '/images/testImage (2).png',
    photo_created_at: '2023-01-10',
    photographer_id: '2023010110',
    photographer_nickname: 'JUN SEO',
    photographer_profile_img: '/images/profile2.png',
    photo_abusing_report_count: 10,
    photographer_photo_abusing_report_count: 10,
  },
  {
    photo_id: '11',
    photo_title: 'Exhibition11',
    photo_description: 'Description11',
    photo_url: '/images/testImage (3).png',
    photo_created_at: '2023-01-11',
    photographer_id: '2023010111',
    photographer_nickname: 'Asher',
    photographer_profile_img: '/images/profile3.png',
    photo_abusing_report_count: 11,
    photographer_photo_abusing_report_count: 11,
  },
  {
    photo_id: '12',
    photo_title: 'Exhibition12',
    photo_description: 'Description12',
    photo_url: '/images/testImage (4).png',
    photo_created_at: '2023-01-12',
    photographer_id: '2023010112',
    photographer_nickname: 'Su bin',
    photographer_profile_img: '/images/profile4.png',
    photo_abusing_report_count: 12,
    photographer_photo_abusing_report_count: 12,
  },
]

export const GUESTBOOK_DUMMY_DATA = [
  {
    guest_book_author_id: 1,
    guest_book_author_profile_img: '/images/profile1.png',
    guest_book_author_nickname: 'JUN SEO',
    guest_book_content: 'Hello World!',
  },
  {
    guest_book_author_id: 2,
    guest_book_author_profile_img: '/images/profile2.png',
    guest_book_author_nickname: 'Han Kyeol',
    guest_book_content: "I'm Sad",
  },
  {
    iguest_book_author_id: 3,
    guest_book_author_profile_img: '/images/profile3.png',
    guest_book_author_nickname: 'Je Koo',
    guest_book_content: "I'm Happy",
  },
  {
    guest_book_author_id: 4,
    guest_book_author_profile_img: '/images/profile4.png',
    guest_book_author_nickname: 'Su bin',
    guest_book_content: "I'm Angry",
  },
  {
    guest_book_author_id: 5,
    guest_book_author_profile_img: '/images/profile1.png',
    guest_book_author_nickname: 'Asher',
    guest_book_content: "I'm Excited",
  },
  {
    guest_book_author_id: 6,
    guest_book_author_profile_img: '/images/profile2.png',
    guest_book_author_nickname: 'JUN SEO',
    guest_book_content: "I'm Tired",
  },
  {
    guest_book_author_id: 7,
    guest_book_author_profile_img: '/images/profile3.png',
    guest_book_author_nickname: 'Han Kyeol',
    guest_book_content: "I'm Sleepy",
  },
  {
    guest_book_author_id: 8,
    guest_book_author_profile_img: '/images/profile4.png',
    guest_book_author_nickname: 'Je Koo',
    guest_book_content: "I'm Hungry",
  },
  {
    guest_book_author_id: 9,
    guest_book_author_profile_img: '/images/profile1.png',
    guest_book_author_nickname: 'Su bin',
    guest_book_content: "I'm Thirsty",
  },
  {
    guest_book_author_id: 10,
    guest_book_author_profile_img: '/images/profile2.png',
    guest_book_author_nickname: 'Asher',
    guest_book_content: "I'm Full",
  },
]
