/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AbJGfdo0WA0
 */
import { CardHeader, CardContent, CardFooter, Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import Image from 'next/image'
import { POST_DUMMY_DATA } from '@/utils/Dummy'

export function Post() {
  return (
    <div className="flex flex-col min-h-screen mb-16">
      <main className="flex-1">
        <div className="container px-4 pb-6 pt-3 mx-auto space-y-6">
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {POST_DUMMY_DATA.map((data) => (
              <Card key={data.photo_id}>
                <CardHeader className="p-3">
                  <div className="flex items-center gap-1 space-x-2 mb-1 p-1">
                    <Image
                      alt="Avatar"
                      className="rounded-full w-10 h-10"
                      height={32}
                      src={data.photographer_profile_img}
                      style={{
                        aspectRatio: '32/32',
                        objectFit: 'cover',
                      }}
                      width={32}
                    />
                    <p className="font-semibold">
                      {data.photographer_nickname}
                    </p>
                  </div>
                  <div className="aspect-[16/9] overflow-hidden rounded-lg">
                    <Image
                      alt="Photo"
                      className="object-cover w-full h-full"
                      height={113}
                      src={data.photo_url}
                      style={{
                        aspectRatio: '200/113',
                        objectFit: 'cover',
                      }}
                      width={200}
                    />
                  </div>
                </CardHeader>
                <CardContent className="px-3 py-2">
                  <p className="text-lg font-semibold mb-1">
                    {data.photo_title}
                  </p>
                  <p className="text-gray-600">{data.photo_description}</p>
                </CardContent>
                <CardFooter className="p-3 flex items-center space-x-2">
                  <Button variant="destructive">삭제</Button>
                  <Button>반려</Button>
                  <Button variant="outline">상세</Button>
                </CardFooter>
              </Card>
            ))}
          </div>
        </div>
      </main>
    </div>
  )
}
