/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AbJGfdo0WA0
 */
'use client'

import { CardHeader, CardContent, CardFooter, Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import Image from 'next/image'
import { useState } from 'react'
import { PostDetailModal } from '../modal/PostDetailModal'
import { type PostDetailType } from '@/types/post'

export function Post({ data }: { data: PostDetailType }) {
  const [isModalOpen, setIsModalOpen] = useState(false)

  function openModal() {
    setIsModalOpen(true)
  }

  function closeModal() {
    setIsModalOpen(false)
  }

  return (
    <>
      <Card key={data.photo_id}>
        <CardHeader className="p-3">
          <div className="flex items-center gap-1 space-x-2 mb-1 p-1">
            <Image
              alt="Avatar"
              className="rounded-full w-10 h-10"
              height={32}
              src={data.photographer_profile_img}
              style={{
                aspectRatio: '32/32',
                objectFit: 'cover',
              }}
              width={32}
            />
            <p className="font-semibold">{data.photographer_nickname}</p>
          </div>
          <div className="aspect-[16/9] overflow-hidden rounded-lg">
            <Image
              alt="Photo"
              className="object-cover w-full h-full"
              height={113}
              src={data.photo_url}
              style={{
                aspectRatio: '200/113',
                objectFit: 'cover',
              }}
              width={200}
            />
          </div>
        </CardHeader>
        <CardContent className="px-3 py-2">
          <p className="text-lg font-semibold mb-1">{data.photo_title}</p>
          <p className="text-gray-600">{data.photo_description}</p>
        </CardContent>
        <CardFooter className="p-3 flex items-center space-x-2">
          <Button variant="destructive">삭제</Button>
          <Button>반려</Button>
          <Button variant="outline" onClick={openModal}>
            상세
          </Button>
        </CardFooter>
      </Card>
      <PostDetailModal
        photo_id={data.photo_id}
        isOpen={isModalOpen}
        closeModal={closeModal}
      />
    </>
  )
}
